export interface ErrorMessage {
  code: number;
  name: string;
  description: string;
  commonCause: string;
  resolution: string;
}

export const ERROR_MESSAGES: Record<string, ErrorMessage> = {
  AlreadyInitialized: {
    code: 1,
    name: 'AlreadyInitialized',
    description: 'The contract has already been initialized and cannot be initialized again.',
    commonCause: 'The frontend attempted to initialize a contract that is already deployed and configured.',
    resolution: 'Skip contract initialization or use the existing deployed contract address.',
  },
  NotInitialized: {
    code: 2,
    name: 'NotInitialized',
    description: 'The contract has not been initialized yet and is not ready for use.',
    commonCause: 'A contract action was called before the initial setup step completed.',
    resolution: 'Ensure the contract has been initialized before invoking other methods.',
  },
  ProposalNotFound: {
    code: 10,
    name: 'ProposalNotFound',
    description: 'The requested proposal could not be found on-chain.',
    commonCause: 'The proposal ID is invalid or the proposal does not exist.',
    resolution: 'Refresh proposal data and verify the proposal ID.',
  },
  ProposalNotActive: {
    code: 11,
    name: 'ProposalNotActive',
    description: 'The proposal is not currently in an active voting state.',
    commonCause: 'The user attempted to vote on a proposal that is pending, passed, rejected, or cancelled.',
    resolution: 'Only vote on active proposals and refresh proposal state.',
  },
  ProposalNotPassed: {
    code: 12,
    name: 'ProposalNotPassed',
    description: 'The proposal did not pass and cannot be executed.',
    commonCause: 'The proposal failed quorum or majority requirements.',
    resolution: 'Check proposal results and review voting thresholds before execution.',
  },
  InvalidTitle: {
    code: 13,
    name: 'InvalidTitle',
    description: 'The proposal title is missing or exceeds the supported length.',
    commonCause: 'User entered an empty title or a title longer than 128 characters.',
    resolution: 'Use a non-empty title with 128 characters or fewer.',
  },
  InvalidDescription: {
    code: 14,
    name: 'InvalidDescription',
    description: 'The proposal description is missing or exceeds the supported length.',
    commonCause: 'User entered an empty description or a description longer than 1024 characters.',
    resolution: 'Use a non-empty description with 1024 characters or fewer.',
  },
  InvalidQuorum: {
    code: 15,
    name: 'InvalidQuorum',
    description: 'The specified quorum is invalid for this proposal.',
    commonCause: 'Quorum is zero, negative, or otherwise unsupported.',
    resolution: 'Choose a quorum greater than zero and within the allowed range.',
  },
  QuorumExceedsSupply: {
    code: 16,
    name: 'QuorumExceedsSupply',
    description: 'The quorum requirement is higher than the total token supply.',
    commonCause: 'Quorum was set too high compared to available voting supply.',
    resolution: 'Set a quorum value that is no larger than the total token supply.',
  },
  InvalidDurationRange: {
    code: 17,
    name: 'InvalidDurationRange',
    description: 'The voting duration is outside the allowed contract limits.',
    commonCause: 'The selected duration is shorter than 60 seconds or longer than the maximum allowed.',
    resolution: 'Choose a valid voting duration within the allowed interval.',
  },
  InsufficientBalance: {
    code: 18,
    name: 'InsufficientBalance',
    description: 'The account balance is too low to create a proposal or perform a token action.',
    commonCause: 'User has insufficient tokens for proposal creation, transfer, or voting operations.',
    resolution: 'Hold enough tokens in the account or use a different account with sufficient balance.',
  },
  ProposalCooldown: {
    code: 19,
    name: 'ProposalCooldown',
    description: 'The proposer is still in a cooldown period and cannot submit another proposal yet.',
    commonCause: 'A proposal was created too recently and the cooldown timer has not expired.',
    resolution: 'Wait until the proposer cooldown period ends before submitting another proposal.',
  },
  VotingNotStarted: {
    code: 20,
    name: 'VotingNotStarted',
    description: 'Voting has not started for this proposal yet.',
    commonCause: 'The proposal voting window is not open yet.',
    resolution: 'Wait until voting begins before casting a vote.',
  },
  VotingPeriodEnded: {
    code: 21,
    name: 'VotingPeriodEnded',
    description: 'The voting period has already ended for this proposal.',
    commonCause: 'The proposal voting window is closed.',
    resolution: 'Review proposal results instead of attempting to vote.',
  },
  VotingStillOpen: {
    code: 22,
    name: 'VotingStillOpen',
    description: 'The proposal voting period is still open and cannot be finalized yet.',
    commonCause: 'A finalization or execution action was attempted before voting ended.',
    resolution: 'Wait for the voting period to finish before finalizing or executing.',
  },
  AlreadyVoted: {
    code: 23,
    name: 'AlreadyVoted',
    description: 'The voter has already voted on this proposal.',
    commonCause: 'The same account attempted to vote more than once on the same proposal.',
    resolution: 'Use a different account or view the existing vote status.',
  },
  NoVotingPower: {
    code: 24,
    name: 'NoVotingPower',
    description: 'The account has no voting power for this proposal.',
    commonCause: 'The voter holds zero governance tokens or voting power is not available.',
    resolution: 'Acquire governance tokens before attempting to vote.',
  },
  AdminVoteRestricted: {
    code: 25,
    name: 'AdminVoteRestricted',
    description: 'The admin is not allowed to vote on their own proposals.',
    commonCause: 'An admin account tried to vote on a proposal it created or controls.',
    resolution: 'Use a non-admin account to vote on the proposal.',
  },
  VoteNotFound: {
    code: 26,
    name: 'VoteNotFound',
    description: 'No vote record was found for the given voter and proposal.',
    commonCause: 'The user has not voted yet or the wrong proposal ID was queried.',
    resolution: 'Confirm the proposal ID and vote status, then vote if needed.',
  },
  NotAdmin: {
    code: 30,
    name: 'NotAdmin',
    description: 'The caller is not authorized as the admin for the contract action.',
    commonCause: 'A restricted admin-only operation was attempted from a non-admin account.',
    resolution: 'Use the admin account or remove the admin-only restriction.',
  },
  InvalidNewAdmin: {
    code: 31,
    name: 'InvalidNewAdmin',
    description: 'The new admin address provided is invalid.',
    commonCause: 'An incorrect or malformed address was supplied when changing admin.',
    resolution: 'Verify and provide a valid Stellar address for the new admin.',
  },
  ContractPaused: {
    code: 40,
    name: 'ContractPaused',
    description: 'The contract is currently paused and cannot perform this action.',
    commonCause: 'The admin paused the contract for maintenance or security reasons.',
    resolution: 'Wait until the contract is unpaused or contact the administrator.',
  },
  NotPaused: {
    code: 41,
    name: 'NotPaused',
    description: 'The contract is not paused and cannot be unpaused.',
    commonCause: 'An unpause action was attempted when the contract is already active.',
    resolution: 'Verify contract state before calling unpause.',
  },
  ArithmeticOverflow: {
    code: 50,
    name: 'ArithmeticOverflow',
    description: 'An arithmetic operation exceeded the contract’s safe numeric range.',
    commonCause: 'A numeric computation overflowed during vote or balance calculations.',
    resolution: 'Retry with valid values and check the contract configuration.',
  },
  InvalidAmount: {
    code: 20,
    name: 'InvalidAmount',
    description: 'The token transfer amount is invalid or non-positive.',
    commonCause: 'The user attempted to send zero or negative tokens.',
    resolution: 'Send a positive amount greater than zero.',
  },
  AllowanceExceeded: {
    code: 22,
    name: 'AllowanceExceeded',
    description: 'The spender’s allowance is insufficient for the requested transfer.',
    commonCause: 'A transfer-with-allowance was attempted without enough approved funds.',
    resolution: 'Increase the allowance or use a smaller transfer amount.',
  },
};
